Optimizing `kronecker_solve`
pyccel/psydac pull request #117
Opened 2021-04-28 19:58 UTC by davschneller

This PR improves the existing `kronecker_solve` method by tying to minimize the number of calls to the solvers (and to MPI in the distributed context), i.e. the whole right-hand side is processed at once for each direction. This all is implemented in the class `KroneckerLinearSolver`.

2021-04-29 07:27 UTC, yguclu commented
@davschneller Thanks for your PR!

Since we use "squash commits" to merge into `devel`, the history of the individual commits will be lost together with their messages. For this reason you should provide more details in the PR's description (in the form of a list), which I will then copy and paste to the squash commit message.

2021-04-29 10:35 UTC, davschneller commented
@yguclu Ok, thanks for letting me know; I'll try to have it done once the PR is ready for merge.

2021-04-30 20:26 UTC, davschneller commented
So, I'm going to post that here, I guess...

**Tests on local machine**
I did do some tests on my local laptop so far (hardware not disclosed so far, OS is Linux, and numpy is from the official Arch Linux repositories), i.e. the MPI operations can be assumed weigh in rather lightly. I did solve the whole problem with 1 process (i.e. no MPI; but it did seem to use threading for LAPACK), and 8 processes (i.e. two MPI processes per sub-communicator), so the MPI cost did not really come into play. I tried to also do it with 64 MPI processes (4 MPI processes per sub-communicator) which oversubscribed the number of CPUs I had at hand (i.e. the results are most likely worse than on well-configured systems), but here MPI dominated.
I did the tests by solving linear systems with a 3-dimensional matrix, i.e. A=A_1⊗A_2⊗A_3 where all A_i have the same size which is also a power of two. Also, the matrices are tridiagonal (i.e. the solve operations should play a time-wise rather little part in the complete operation), and we use an in-place banded solver from the LAPACK pack I had at hand. The tests were each done 1000 times.

Key insights:

size (128,128,128), no MPI:
354 ms vs 153 ms (i.e. about 2,3× speedup)
(remark: the new method spends about 80% of its time in the solve operation, and uses most of the remaining time for re-ordering the dimensions and copying memory ; the old method spends about 60% in the solve method)

size (128,128,128), 8 MPI processes:
112 ms vs 40 ms (i.e. about 2,8× speedup)
(remark: the new method spent about 45% of its time in the MPI Alltoallv and the re-ordering of the blocks, and about 20% in re-ordering the dimensions and memory copying and only about 33% in the solve part ; interestingly enough, the old method spends percentually more time in the solve operations than in the Allgatherv, but still spends more time in each of these)

size (128,128,128), 64 MPI processes:
925 ms vs 37 ms (i.e. about 25× speedup; but again, this is more a synthetic test case)
(remark: the new method spent about 75% of its time in the MPI Alltoallv, the re-ordering of the blocks and dimension re-ordering took only 4% to 5%, the actual solve only about 5% of the overall time ; the old method spends about 85% in the Allgatherv part)

It should be noted that the new method, when comparing no MPI to 8 MPI processes, then the 8 MPI process variant is about 3,8× as fast. This may have several reasons, including that the no MPI version seemed to use threads for solving the right-hand sides. The 64 MPI process version cannot be compared very well, since it used a single CPU core to host about 8 processes.

**Plots (with legends placed around)**

Here is a plot of the computation times, for the old and new methods:
![Figure_1](https://user-images.githubusercontent.com/12698011/116748205-61f2f880-a9ff-11eb-82c8-0da1fa259944.png)
Note that the 64 MPI process lines are naturally higher than the rest.

Next, some plot which shows how much time is spent in the MPI calls **(NOTE: a lower number here can still indicate that the method takes much longer to complete than other methods; it would be more accurate to place every line of these graphs in different plots)**:
![Figure_2](https://user-images.githubusercontent.com/12698011/116749378-22c5a700-aa01-11eb-9070-76572f1d2825.png)
One could say, lower is better. Again, the 64 MPI process lines are included, but as it can be seen, in these artificial scenarios, MPI takes most of the time. The no-MPI line is also included at 0%, for completeness. The old methods seem generally to use a bit more MPI than the new versions, except that one exception at 128.

And here some plot which shows how much time is spend in the `DirectSolver`, in our case a banded solver **(NOTE: a lower number here can still indicate that the method takes much longer to complete than other methods; it would be more accurate to place every line of these graphs in different plots)**:
![Figure_3](https://user-images.githubusercontent.com/12698011/116750073-31f92480-aa02-11eb-8004-be1997fb7c54.png)
One could say, higher is better, because then our time is well-spent. Again, at 128, there is some drop to be seen. This drop also occurs in the no-MPI line (the orange one), one may assume that re-ordering the data begins to take more time here. The old method seems to spend more time in the solvers with the size increasing, but this is relativized again, when looking at the absolute performance.

**Tests on the cluster**
I also took two nodes from the CoolMUC2 cluster and used Intel Python 3.6. The interconnect was potentially a bit broken/there were problems with Intel MPI 2019. Nonetheless, the few results I got with 112 MPI processes (on two nodes) a few results; namely: the old method took too long, so I aborted the process, after the test took about 1/2h with (32,32,32). For the new method, I got results for (128,128,128). In all the cases with 112 processes, MPI takes up most of the runtime. For the old method, we spend 70% of the time in the Allgatherv, and 30% of the time in the ghost region updates. For the new method, it is the ghost region updates with about 70% (MPI Barrier), followed by about 30% for the Alltoallv in the `KroneckerLinearSolver`. Again, the interconnect might be slower here than it could be. When testing on (128,128,128) with only 2 processes (also, only the new method), the solve is again the part that takes up most of the time. Both of these runs for (128,128,128) took longer than on my local machine (546 ms for two processes, 600 ms for 112 processes).

2021-05-03 13:04 UTC, yguclu requested changes
Good job @davschneller! i have a few comments.

2021-05-03 13:04 UTC, yguclu commented on psydac/linalg/kron.py
> +        given that the data is already in memory.
This docstring should be clarified: the same equation is solved for multiple right-hand-side vectors simultaneously.

2021-05-03 13:04 UTC, yguclu commented on psydac/linalg/kron.py
> +            The number of right-hand sizes we want to solve. Equals the product of the
Typo? sizes -> sides

2021-05-03 13:04 UTC, yguclu commented on psydac/linalg/kron.py
> +            The number of right-hand sizes we want to solve. Equals the product of the
Typo? sizes -> sides

2021-05-03 13:30 UTC, davschneller commented on psydac/linalg/kron.py
> +                The data which is used for solving. All columns to be solved are ordered contiguously.
That kind of the case. It _has_ this ordering, but `workmem` is actually passed as a one-dimensional array which has all columns written one after another contiguously in memory. It is then re-interpreted as two-dimensional data, with the size of the columns as one dimension, and all other dimensions are combined into another one (we don't care for the internal ordering of them), so, the indexing is then like `workmem[i, :]` where `i` is an index over all columns (but not specified any further). (we also convert to FORTRAN order after that all)

2021-05-03 13:31 UTC, davschneller commented on psydac/linalg/kron.py
> +        #       _contiguous_to_blocked methods into the MPI implementation.
Yes, this is about what I thought about there. In our case, we might get away with a `Create_vector` already possibly.

2021-05-03 14:07 UTC, davschneller commented on psydac/linalg/kron.py
> +            The number of right-hand sizes we want to solve. Equals the product of the
Yes, typo. Should be fixed by now.

2021-05-03 14:41 UTC, davschneller commented on psydac/linalg/direct_solvers.py
> +            _, self._sinfo = dgbtrs(self._bmat, self._l, self._u, rhs, self._ipiv, overwrite_b=True, trans=transposed)
Well yes, it was meant to be this way... It's changed now and new tests have been added.

2021-05-03 14:44 UTC, davschneller commented on psydac/linalg/kron.py
> +        #       _contiguous_to_blocked methods into the MPI implementation.
Should I add this to the current code in this PR (in addition to the existing code paths or as substitute for them)? Or shall this be done in a later PR?

2021-05-04 09:02 UTC, yguclu approved these changes

2021-05-04 09:10 UTC, saidctb approved these changes

2021-05-04 09:11 UTC, yguclu commented on psydac/linalg/kron.py
> +                The data which is used for solving. All columns to be solved are ordered contiguously.
Thanks for the explanation.

2021-05-04 09:23 UTC, merged