Add `BlockDiagonalSolver` for combining `LinearSolver`s
pyccel/psydac pull request #120
Opened 2021-05-05 09:55 UTC by davschneller

This PR introduces a new class `BlockDiagonalSolver`. The features are:
* Applies several `LinearSolvers` to parts of a `BlockVector`.
* Works as a `LinearSolver` on `BlockVectorSpace`s.
* Includes tests.

2021-05-05 14:32 UTC, yguclu requested changes
Thanks @davschneller, this is very neat. I have a couple of comments

2021-05-05 14:32 UTC, yguclu commented on psydac/linalg/tests/test_block.py
> +    # set seed for reproducability
Typo: reproducability -> reproducibility

2021-05-05 14:32 UTC, yguclu commented on psydac/linalg/tests/test_block.py
> +    # set seed for reproducability
Typo

2021-05-05 14:32 UTC, yguclu commented on psydac/linalg/tests/test_block.py
> +    # set seed for reproducability
Typo

2021-05-05 14:32 UTC, yguclu commented on psydac/linalg/tests/test_block.py
> +    # set seed for reproducability
Typo

2021-05-05 14:32 UTC, yguclu commented on psydac/linalg/tests/test_block.py
> +    # set seed for reproducability
Typo

2021-05-05 14:32 UTC, yguclu commented on psydac/linalg/tests/test_block.py
> +    # set seed for reproducability
Typo

2021-05-05 14:32 UTC, yguclu commented on psydac/linalg/tests/test_block.py
> +    # set seed for reproducability
Typo: reproducability -> reproducibility

2021-05-05 18:03 UTC, davschneller commented on psydac/linalg/block.py
> +            out *= 0.0
Yes, that should be in there; thanks for the notice; it has been changed with the latest commit. Tests and documentation have been updated as well to include the `out is rhs` and `out is not None and out is not rhs` case.

2021-05-06 08:11 UTC, yguclu approved these changes
Very good! Thanks for the changes

2021-05-06 08:56 UTC, saidctb approved these changes

2021-05-06 09:17 UTC, merged