uptating ghost regions before assembling a form
pyccel/psydac pull request #281
Opened 2023-03-10 14:38 UTC by vcarlier

Added the update of ghost regions in assemble for linear and bilinear forms.
Added a test showing how the error could show up

2023-03-13 18:19 UTC, yguclu approved these changes
@vcarlier Thanks for investigating the problem and fixing it! The PR looks good to me

2023-03-14 08:59 UTC, yguclu requested changes

2023-03-14 08:59 UTC, yguclu commented on psydac/api/tests/test_assembly.py
Could you also test if norms (i.e. a `DiscreteFunctional`) have the same problem? I suspect they do.

2023-03-14 14:15 UTC, vcarlier commented on psydac/api/tests/test_assembly.py
The problem was there, I fixed it and add a small test where the bug was showing up

2023-03-14 15:08 UTC, yguclu commented on psydac/api/tests/test_assembly.py
Great, thanks!

2023-03-14 15:14 UTC, yguclu approved these changes

2023-03-14 16:20 UTC, saidctb approved these changes

2023-03-14 17:29 UTC, merged