Construct de Rham sequence with a NURBS/spline mapping
pyccel/psydac pull request #366
Opened 2023-12-06 16:14 UTC by vcarlier

Solve #243:

* In the class method `Geometry.from_discrete_mapping` set the `SplineMapping` as the `callable_mapping` of the symbolic mapping before calling the constructor of `Geometry`.
* Modify the constructor of class `Pushforward` to accept a symbolic mapping having a `SplineMapping` as its callable mapping. Accordingly, remove the assert which was requiring the mapping to be analytic.
* Add some tests is `psydac.api.tests.test_build_derham_mapping.py` to prove that this method works.

2023-12-13 13:53 UTC, yguclu commented on psydac/api/postprocessing.py
Can you please check if the `mapping` argument can be of type `SplineMapping`? If not, we could simplify the code a bit.

2023-12-13 13:54 UTC, yguclu commented on psydac/feec/pushforward.py
Also here. Can you please check if the `mapping` argument can be of type `SplineMapping`? If not, we could simplify the code a bit.

2023-12-14 13:49 UTC, vcarlier commented on psydac/api/postprocessing.py
Apparently it's usefull in the multipatch setting where the mapping of each patch could be represented as a SplineMapping if I understood correctly.

2023-12-14 13:49 UTC, vcarlier commented on psydac/feec/pushforward.py
Same : Apparently it's usefull in the multipatch setting where the mapping of each patch could be represented as a `SplineMapping` if I understood correctly.

2024-01-24 13:31 UTC, yguclu requested changes

2024-01-25 14:41 UTC, vcarlier commented on psydac/feec/pushforward.py
>              # No support for non analytical mappings for now
Done in [fb754be](https://github.com/pyccel/psydac/pull/366/commits/fb754be254176f624e2730bec5e89509a5a2134c)

2024-01-25 14:41 UTC, vcarlier commented on psydac/cad/geometry.py
> +        Parameters
Done in [fb754be](https://github.com/pyccel/psydac/pull/366/commits/fb754be254176f624e2730bec5e89509a5a2134c)

2024-01-25 14:41 UTC, vcarlier commented on psydac/cad/geometry.py
> +            The Mapping from the unit square to to physical domain.
Done in [fb754be](https://github.com/pyccel/psydac/pull/366/commits/fb754be254176f624e2730bec5e89509a5a2134c)

2024-01-25 14:42 UTC, vcarlier commented on psydac/api/tests/test_build_derham_mapping.py
> +    #test_build_derham_spline_mapping_id_3d([2,3,4], [10,11,3], [True,False,False])
Done in [fb754be](https://github.com/pyccel/psydac/pull/366/commits/fb754be254176f624e2730bec5e89509a5a2134c)

2024-01-25 14:43 UTC, vcarlier commented on psydac/cad/geometry.py
> +            M        = Mapping('mapping' + name, dim=1)
Done in [fb754be](https://github.com/pyccel/psydac/pull/366/commits/fb754be254176f624e2730bec5e89509a5a2134c). 

It was probably just a default name but I have no clue why `_0`.

2024-01-28 23:09 UTC, yguclu approved these changes

2024-01-29 06:41 UTC, yguclu approved these changes

2024-01-29 07:39 UTC, merged