Provide alternative shell command for discovering HDF5_DIR on Ubuntu/Debian systems
pyccel/psydac pull request #399
Opened 2024-04-03 06:08 UTC by kvrigor

On Ubuntu 22.04, `h5pcc -showconfig` gives the wrong installation point required by `h5py`:

```sh

            SUMMARY OF THE HDF5 CONFIGURATION
            =================================

General Information:
-------------------
                   HDF5 Version: 1.10.7
                  Configured on: Wed, 08 Dec 2021 23:33:27 +0000
                  Configured by: Debian
                    Host system: x86_64-pc-linux-gnu
              Uname information: Debian
                       Byte sex: little-endian
             Installation point: /usr
                    Flavor name: openmpi
```

`pip3 install h5py` will look for `libhdf5.so` which is at `/usr/lib/x86_64-linux-gnu/hdf5/openmpi`, not `/usr`. On Ubuntu/Debian one could directly extract `HDF5_DIR` with the command

```sh
export HDF5_DIR=$(dpkg -L libhdf5-openmpi-dev | grep libhdf5.so | xargs dirname)
```

I wonder if we should still suggest `h5pcc -showconfig` which doesn't really work and may trip users (e.g. #219). The command above may look "hacky", but I believe its robust and would still work for future Ubuntu/Debian releases unless `libhdf5-openmpi-dev` has been renamed—in such case the README has to be updated anyway to change the parallel HDF5 library name for the `apt install` step.

2024-04-10 16:56 UTC, yguclu requested changes
The changes look good to me! Thanks @kvrigor!

If the `h5pcc` command does not provide the correct information, I suggest that we remove it from the README.

2024-04-10 16:58 UTC, yguclu commented
@pyccel/psydac-dev If you use a Ubuntu/Debian OS, can you please verify that the new command works for you?

2024-04-11 06:10 UTC, kvrigor commented
> If the h5pcc command does not provide the correct information, I suggest that we remove it from the README.

Done 👍

Also I've applied the `HDF5_DIR` command to [continuous-integration.yml](https://github.com/pyccel/psydac/pull/399/files#diff-c471496bcb3ed47397b73d2e3e3aa41a8a679c86accaed9e05676fd9d5987434R85). So far it could parse the path correctly.

2024-04-11 11:52 UTC, yguclu approved these changes

2024-04-11 12:05 UTC, yguclu commented
> > If the h5pcc command does not provide the correct information, I suggest that we remove it from the README.
> 
> Done 👍
> 
> Also I've applied the `HDF5_DIR` command to [continuous-integration.yml](https://github.com/pyccel/psydac/pull/399/files#diff-c471496bcb3ed47397b73d2e3e3aa41a8a679c86accaed9e05676fd9d5987434R85). So far it could parse the path correctly.

I have just realized that in the continuous integration we do not use `brew info hdf5-mpi` on macOS, but rather the command
```sh
HDF5_DIR=$((h5pcc -showconfig -echo || true) | grep "Installation point:" | cut -d ":" -f2 | tr -d " ")
```
which was given by @nhamidn in [commit c6e4cf1](https://github.com/pyccel/psydac/pull/200/commits/c6e4cf1713925eab7cbcab1d42f9ae8236c317b2). Maybe a similar command can be made to work with `brew`?

2024-04-11 15:59 UTC, yguclu commented
> > Maybe a similar command can be made to work with brew?
> 
> I've no macOS to test on, but perhaps `brew list hdf5-mpi | grep libhdf5.so | xargs dirname` may work?

This one seems to work:
```sh
brew list hdf5-mpi | grep "libhdf5.dylib" | xargs dirname | xargs dirname
```

2024-04-12 15:53 UTC, kvrigor commented
`HDF5_DIR=$(brew list hdf5-mpi | grep "libhdf5.dylib" | xargs dirname)` seems sufficient for `h5py`; the macOS test [passed](https://github.com/pyccel/psydac/actions/runs/8664454949/job/23760901726?pr=399) with this change 👍

I've modified the `README` once more—removing unnecessary details about the `HDF5_DIR`. I hope this makes the [Installing the library](https://github.com/pyccel/psydac/pull/399/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R86) step flow better.

2024-04-13 11:25 UTC, yguclu approved these changes
Excellent! Thanks!

2024-04-13 11:45 UTC, merged