Use branch "real_coord" of SymPDE
pyccel/psydac pull request #445
Opened 2024-10-16 12:21 UTC by yguclu

2024-12-02 10:37 UTC, e-moral-sanchez commented
This PR is linked to https://github.com/pyccel/sympde/pull/170 .

After the change that coordinates must be real, the symbols used in the tests to write the exact solution must also be declared as real.

2025-02-06 09:42 UTC, e-moral-sanchez requested changes

2025-02-06 09:42 UTC, e-moral-sanchez commented on pyproject.toml
> +    'sympde @ https://github.com/pyccel/sympde/archive/refs/heads/real_coord.zip',
Just as a reminder, we need to revert this line before merging

2025-02-12 16:10 UTC, yguclu commented on pyproject.toml
> +    'sympde @ https://github.com/pyccel/sympde/archive/refs/heads/real_coord.zip',
And by the way, yes we should bump up SymPDE version to 0.17.1

2025-02-12 16:10 UTC, campospinto commented on pyproject.toml
> +    'sympde @ https://github.com/pyccel/sympde/archive/refs/heads/real_coord.zip',
Oh, I see that I need to review the Sympde PR... I'll do it asap

2025-02-12 16:11 UTC, e-moral-sanchez commented on pyproject.toml
> +    'sympde @ https://github.com/pyccel/sympde/archive/refs/heads/real_coord.zip',
Thanks for taking a look. This PR is ready.

2025-03-05 10:40 UTC, campospinto approved these changes

2025-03-05 21:20 UTC, yguclu commented on pyproject.toml
> +    'sympde @ https://github.com/pyccel/sympde/archive/refs/heads/real_coord.zip',
We now use SymPDE version 0.19.1

2025-03-05 21:29 UTC, merged