Fix Greville point collocation matrix for single grid point case
pyccel/psydac pull request #446
Opened 2024-10-16 13:51 UTC by maxlin-ipp

Previously, in the case when `self.greville.size == 1`, `collocation_matrix` would return an empty matrix.

Now, if the grid has a single Greville point, the collocation matrix is simplified to a 1x1 matrix with a value of 1.

2025-02-19 13:41 UTC, yguclu requested changes

2025-02-19 13:41 UTC, yguclu commented on psydac/fem/splines.py
> +            )
I suggest that this case be handled inside the function `collocation_matrix` itself.

2025-02-26 14:26 UTC, campospinto reviewed
I agree with Yaman's suggestion

2025-03-05 18:32 UTC, yguclu approved these changes

2025-03-05 18:33 UTC, yguclu commented on psydac/fem/splines.py
> +            )
Done in df5ed36

2025-03-05 18:35 UTC, merged